import numpy as np
a=np.array([[1,2],[2,2]])
print(a.shape)
b=np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(b.shape)
d=np.arange(20)
d.resize(5,6)
print(d)
print(d.shape,d.size)
c=d.reshape((6,5),order="C")
print(c)
print(c.shape,c.size)
f=d.reshape((6,5),order="F")
print(f)
print(f.shape,f.size)